release: python manage.py migrate
{% if cookiecutter.use_async == "y" -%}
web: gunicorn {{ cookiecutter.project_slug }}.asgi:application -k uvicorn.workers.UvicornWorker
{%- else  %}
web: gunicorn {{ cookiecutter.project_slug }}.wsgi:application
{%- endif %}
{% if cookiecutter.use_celery == "y" -%}
worker: celery worker --app={{ cookiecutter.project_slug }}.celery_app --loglevel=info
beat: celery beat --app={{ cookiecutter.project_slug }}.celery_app --loglevel=info
{%- endif %}
